version: '3.5'
services:
 movie-analyst-api:
    image: elielbloemer/image-api
    container_name: container-api
    ports:
            - "3000:3000"
 movie-analyst-ui:
   image: elielbloemer/image-ui
   container_name: container-ui
   ports: 
           - "8000:8000"
 db:
   image: mysql:latest
   container_name: movie_db
   ports:
      - "3306:3306"
   volumes: 
      - ./home/ebloemer/ramp-up-v1.0/movie-analyst-database:/databases/schema.sql
      - ./home/ebloemer/ramp-up-v1.0/movie-analyst-database:/databases/data.sql
   environment:
      MYSQL_ROOT_PASSWORD: brasil
      MYSQL_DATABASE: movie_db
 
